ALTER TABLE torrents ADD COLUMN title TEXT NOT NULL DEFAULT '';
ALTER TABLE torrents ADD COLUMN data TEXT NOT NULL DEFAULT '';
ALTER TABLE torrents ADD COLUMN poster TEXT NOT NULL DEFAULT '';
ALTER TABLE torrents ADD COLUMN category TEXT NOT NULL DEFAULT '';
